### ISSUE TITLE
Add Typescript

### ISSUE THREAD

**Issue by IrvingArmenta** [brunobertolini/pagix#12]
Hello, I already added the typings for this in a local branch, perhaps you'd like to check them, 
just let me push and do a merge request.

**Comment by SimeonC** [comment]
@IrvingArmenta Normally you should create a fork of the repository and create a pull request from there. I'm interested in the types for this too (if you don't want to do that let me know and I'll create a pull request).

I too had to add types locally, here's my definition for comparison, the only difference between this (which is used in a `definitions.d.ts` file) and implementation in the library is removing the `declare module` wrapper.

https://gist.github.com/SimeonC/60e2679585c4fda965c5dbf823131851

**Comment by SimeonC** [comment]
I found some bugs so I added the types alongside my PR fixing the bugs.
